#!/usr/bin/env bash

if [[ -d vim ]]; then
  (cd vim && hg pull -u)
else
  hg clone https://tkztmk@bitbucket.org/tkztmk/vim
fi
rm -Rf vim-build
cp -R vim vim-build
cd vim-build/src
autoconf
CFLAGS='-O1' ./configure --prefix=$HOME/local/vim/hg \
        --with-features=big --with-compiledby='Takezoe Tomoaki' \
        --enable-gpm --enable-acl --with-x=no --disable-gui --enable-multibyte \
        --enable-cscope --disable-netbeans --disable-perlinterp \
        --disable-pythoninterp --disable-python3interp --disable-rubyinterp \
        --disable-luainterp
make -j1
make install

